<a href="https://colab.research.google.com/github/bym0701/SK_AI_Dream_Camp_begginer/blob/main/03)_%5B%EC%8B%A4%EC%8A%B5%5D_Pandas_%EC%A1%B0%ED%9A%8C%2C_%EC%A0%95%EB%A0%AC%2C_%EC%A1%B0%EA%B1%B4_%ED%95%84%ED%84%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
import seaborn as sns

In [7]:
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
#데이터 분석!
#주요 목표

#Pandas를 활용하여 타이타닉호 생존자, 사망자 데이터를 분석합니다.
#데이터를 토대로 생존율이 높은 승객, 생존율이 낮은 승객은 누구인지 판단합니다.

#head() 앞 부분 / tail() 뒷 부분 조회
#default 옵션 값으로 5개의 행이 조회됩니다.
#괄호 안에 숫자를 넣어 명시적으로 조회하고 싶은 행의 갯수를 지정할 수 있습니다.
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [10]:
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [11]:
df.tail(7)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
884,0,3,male,25.0,0,0,7.050,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.125,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.450,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.750,Q,Third,man,True,NaN,Queenstown,no,True

In [12]:
#info()
#컬럼별 정보(information)를 보여줍니다.
#데이터의 갯수, 그리고 데이터 타입(dtype)을 확인할 때 사용합니다.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [13]:
#object 타입은 쉽게 문자열이라고 생각하면 됩니다.
#그런데, category 타입도 있습니다. category 타입은 문자열이지만, '남자' / '여자'처럼 카테고리화 할 수 있는 컬럼을 의미 합니다. 나중에 별도로 다루겠습니다.

#value_counts()
#column 별 값의 분포를 확인할 때 사용합니다.

#남자, 여자, 아이의 데이터 분포를 확인하고 싶다면 다음과 같이 실행합니다.
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [14]:
#연습문제
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:
#embark_town은 승객의 탑승 항구를 나타내는 column 입니다. 탑승 항구별 승객 데이터 분포를 확인해 주세요.
df['embark_town'].value_counts(True)

embark_town
Southampton    0.724409
Cherbourg      0.188976
Queenstown     0.086614
Name: proportion, dtype: float64

In [16]:
#who 컬럼에 대한 데이터 분포를 확인해 주세요
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [17]:
#속성: Attributes
#속성 값은 함수형으로 조회하지 않습니다.

#자주 활용하는 DataFrame은 속성 값들은 다음과 같습니다.

#ndim
#shape
#index
#columns
#values
#T

#차원을 나타냅니다. DataFrame은 2가 출력됩니다.
df.ndim

2

In [18]:
#(행, 열) 순서로 출력됩니다.
df.shape

(891, 15)

In [19]:
#index는 기본 설정된 RangeIndex가 출력됩니다.
df.index

RangeIndex(start=0, stop=891, step=1)

In [20]:
#columns는 열을 출력 합니다.
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [22]:
#values는 모든 값을 출력하며, numpy array 형식으로 출력됩니다.
df.values

array([[0, 3, 'male', ..., 'Southampton', 'no', False],
       [1, 1, 'female', ..., 'Cherbourg', 'yes', False],
       [1, 3, 'female', ..., 'Southampton', 'yes', True],
       ...,
       [0, 3, 'female', ..., 'Southampton', 'no', False],
       [1, 1, 'male', ..., 'Cherbourg', 'yes', True],
       [0, 3, 'male', ..., 'Queenstown', 'no', True]], dtype=object)

In [23]:
#T: 전치 (Transpose) 는 Index와 Column의 축을 교환합니다.
df.T

,0,1,2,3,4,5,6,7,8,9,...,881,882,883,884,885,886,887,888,889,890
survived,0,1,1,1,0,0,0,0,1,1,...,0,0,0,0,0,0,1,0,1,0
pclass,3,1,3,1,3,3,1,3,3,2,...,3,3,2,3,3,2,1,3,1,3
sex,male,female,female,female,male,male,male,male,female,female,...,male,female,male,male,female,male,female,female,male,male
age,22.0,38.0,26.0,35.0,35.0,NaN,54.0,2.0,27.0,14.0,...,33.0,22.0,28.0,25.0,39.0,27.0,19.0,NaN,26.0,32.0
sibsp,1,1,0,1,0,0,0,3,0,1,...,0,0,0,0,0,0,0,1,0,0
parch,0,0,0,0,0,0,0,1,2,0,...,0,0,0,0,5,0,0,2,0,0
fare,7.25,71.2833,7.925,53.1,8.05,8.4583,51.8625,21.075,11.1333,30.0708,...,7.8958,10.5167,10.5,7.05,29.125,13.0,30.0,23.45,30.0,7.75
embarked,S,C,S,S,S,Q,S,S,S,C,...,S,S,S,S,Q,S,S,S,C,Q
class,Third,First,Third,First,Third,Third,First,Third,Third,Second,...,Third,Third,Second,Third,Third,Second,First,Third,First,Third
who,man,woman,woman,woman,man,man,man,child,woman,child,...,man,woman,man,man,woman,man,woman,woman,man,man
adult_male,True,False,False,False,True,True,True,False,False,False,...,True,False,True,True,False,True,False,False,True,True
deck,NaN,C,NaN,C,NaN,NaN,E,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,B,NaN,C,NaN
embark_town,Southampton,Cherbourg,Southampton,Southampton,Southampton,Queenstown,Southampton,Southampton,Southampton,Cherbourg,...,Southampton,Southampton,Southampton,Southampton,Queenstown,Southampton,Southampton,Southampton,Cherbourg,Queenstown
alive,no,yes,yes,yes,no,no,no,no,yes,yes,...,no,no,no,no,no,no,yes,no,yes,no
alone,False,False,True,False,True,True,True,False,False,False,...,True,True,True,True,False,True,True,False,True,True

In [24]:
#타입 변환 (astype)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [25]:
#int32로 변경
df['pclass'].astype('int32').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: int32

In [26]:
#float32로 변경
df['pclass'].astype('float32').head()

0    3.0
1    1.0
2    3.0
3    1.0
4    3.0
Name: pclass, dtype: float32

In [27]:
#object로 변경
df['pclass'].astype('str').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: object

In [28]:
#category로 변경.

#category로 변경시에는 Categories가 같이 출력 됩니다.
df['pclass'].astype('category').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: category
Categories (3, int64): [1, 2, 3]

In [29]:
#정렬 (sort)
#sort_index: index 정렬
#index 기준으로 정렬합니다. (기본 오름차순이 적용되어 있습니다.
#내림차순 정렬을 적용하려면, ascending=False를 옵션 값으로 설정합니다.
df.sort_index().head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [30]:
df.sort_index(ascending=False).head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True

In [31]:
#sort_values: 값에 대한 정렬
#값을 기준으로 행을 정렬합니다.
#by에 기준이 되는 행을 설정합니다.
#by에 2개 이상의 컬럼을 지정하여 정렬할 수 있습니다.
#오름차순/내림차순을 컬럼 별로 지정할 수 있습니다.
df.sort_values(by='age').head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False

In [32]:
#내림차순 정렬: ascending=False
df.sort_values(by='age', ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [33]:
#문자열 컬럼도 오름차순/내림차순 정렬이 가능하며 알파벳 순서로 정렬됩니다.
df.sort_values(by='class', ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
511,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
500,0,3,male,17.0,0,0,8.6625,S,Third,man,True,NaN,Southampton,no,True
501,0,3,female,21.0,0,0,7.7500,Q,Third,woman,False,NaN,Queenstown,no,True
502,0,3,female,NaN,0,0,7.6292,Q,Third,woman,False,NaN,Queenstown,no,True

In [34]:
#2개 이상의 컬럼을 기준으로 값 정렬 할 수 있습니다.
df.sort_values(by=['fare', 'age']).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
302,0,3,male,19.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
271,1,3,male,25.0,0,0,0.0,S,Third,man,True,NaN,Southampton,yes,True
179,0,3,male,36.0,0,0,0.0,S,Third,man,True,NaN,Southampton,no,True
822,0,1,male,38.0,0,0,0.0,S,First,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0,S,First,man,True,A,Southampton,no,True

In [36]:
#오름차순/내림차순 정렬도 컬럼 각각에 지정해 줄 수 있습니다.
df.sort_values(by=['fare', 'age'], ascending=[False, True]).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
88,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False

In [37]:
#연습문제
#tips 데이터는 미국 레스토랑의 매출과 웨이터에게 지불한 팁을 나타내는 데이터입니다.

tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [38]:
#total_bill과 tip에 대한 내림차순 정렬을 해주세요
#상위 10개만 출력하세요
tips.sort_values(by=['total_bill', 'tip'], ascending=[False, False]).head(10)

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
156       48.17   5.00    Male     No   Sun  Dinner     6
182       45.35   3.50    Male    Yes   Sun  Dinner     3
102       44.30   2.50  Female    Yes   Sat  Dinner     3
197       43.11   5.00  Female    Yes  Thur   Lunch     4
142       41.19   5.00    Male     No  Thur   Lunch     5
184       40.55   3.00    Male    Yes   Sun  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4

In [39]:
#size를 기준으로 내림차순, tip을 기준으로는 오름차순 정렬을 해주세요
#상위 10개의 데이터만 출력하세요
tips.sort_values(by=['size', 'tip'], ascending=[False, True]).head(10)

     total_bill   tip     sex smoker   day    time  size
125       29.80  4.20  Female     No  Thur   Lunch     6
143       27.05  5.00  Female     No  Thur   Lunch     6
156       48.17  5.00    Male     No   Sun  Dinner     6
141       34.30  6.70    Male     No  Thur   Lunch     6
187       30.46  2.00    Male    Yes   Sun  Dinner     5
216       28.15  3.00    Male    Yes   Sat  Dinner     5
142       41.19  5.00    Male     No  Thur   Lunch     5
185       20.69  5.00    Male     No   Sun  Dinner     5
155       29.85  5.14  Female     No   Sun  Dinner     5
153       24.55  2.00    Male     No   Sun  Dinner     4

In [40]:
#Indexing, Slicing, 조건 필터링
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [41]:
#loc - indexing / slicing
#indexing과 slicing을 할 수 있습니다.
#slicing은 [시작(포함): 끝(포함)] 규칙에 유의합니다. 둘 다 포함 합니다.
df.loc[5, 'class']

'Third'

In [42]:
df.loc[2:5, ['age', 'fare', 'who']]

    age     fare    who
2  26.0   7.9250  woman
3  35.0  53.1000  woman
4  35.0   8.0500    man
5   NaN   8.4583    man

In [43]:
df.loc[2:5, 'class':'deck'].head()

   class    who  adult_male deck
2  Third  woman       False  NaN
3  First  woman       False    C
4  Third    man        True  NaN
5  Third    man        True  NaN

In [44]:
df.loc[:6, 'class':'deck']

   class    who  adult_male deck
0  Third    man        True  NaN
1  First  woman       False    C
2  Third  woman       False  NaN
3  First  woman       False    C
4  Third    man        True  NaN
5  Third    man        True  NaN
6  First    man        True    E

In [46]:
#연습문제
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [47]:
#다음과 같은 결과를 가지도록 인덱싱 혹은 슬라이싱 하세요
df[3:8]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [48]:
df.loc[:5, 'pclass':'fare']

   pclass     sex   age  sibsp  parch     fare
0       3    male  22.0      1      0   7.2500
1       1  female  38.0      1      0  71.2833
2       3  female  26.0      0      0   7.9250
3       1  female  35.0      1      0  53.1000
4       3    male  35.0      0      0   8.0500
5       3    male   NaN      0      0   8.4583

In [49]:
df.loc[2:11:2, ['age','who']]

     age    who
2   26.0  woman
4   35.0    man
6   54.0    man
8   27.0  woman
10   4.0  child

In [50]:
#loc - 조건 필터
#boolean index을 만들어 조건에 맞는 데이터만 추출해 낼 수 있습니다.
cond = (df['age'] >= 70)
cond

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [51]:
df.loc[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [52]:
#loc - 다중 조건
#다중 조건은 먼저 condition을 정의하고 & 와 | 연산자로 복합 조건을 생성합니다.

# 조건1 정의
cond1 = (df['fare'] > 30)

# 조건2 정의
cond2 = (df['who'] == 'woman')

In [53]:
df.loc[cond1 & cond2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

In [54]:
df.loc[cond1 | cond2]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [56]:
#조건 필터 후 데이터 대입
cond = (df['age'] >= 70)
cond

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [57]:
# 조건 필터
df.loc[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
745,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [59]:
#나이 컬럼만 가져옵니다.
df.loc[cond, 'age']

96     71.0
116    70.5
493    71.0
630    80.0
672    70.0
745    70.0
851    74.0
Name: age, dtype: float64

In [60]:
#조건 필터 후 원하는 값을 대입할 수 있습니다. (단일 컬럼 선택에 유의)
df.loc[cond, 'age'] = -1

In [61]:
df.loc[cond]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,-1.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,-1.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,-1.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,-1.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
672,0,2,male,-1.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
745,0,1,male,-1.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
851,0,3,male,-1.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [62]:
#연습문제
#데이터를 다시 로드 합니다.

df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [63]:
#다음 조건을 만족하는 코드를 입력하세요.

#나이가 30살 이상 남자 승객 조건 필터링
#fare를 많이 낸 순서로 내림차순 정렬
#상위 10개를 출력

cond1 = (df['age']>=30)
cond2 = (df['sex']=='male')
df.loc[cond1&cond2].sort_values(by='fare', ascending=False).head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
332,0,1,male,38.0,0,1,153.4625,S,First,man,True,C,Southampton,no,False
660,1,1,male,50.0,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
390,1,1,male,36.0,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
659,0,1,male,58.0,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
698,0,1,male,49.0,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
544,0,1,male,50.0,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
245,0,1,male,44.0,2,0,90.0000,Q,First,man,True,C,Queenstown,no,False

In [64]:
#나이가 20살 이상 40살 미만인 승객
#pclass가 1등급 혹은 2등급인 승객
#열(column)은 survived, pclass, age, fare 만 나오게 출력
#10개만 출력
cond1 = ((df['age']>=20)&(df['age']<40))
cond2 = ((df['pclass']==1)|(df['pclass']==2))
df.loc[cond1&cond2, ['survived', 'pclass', 'age', 'fare']].head(10)

    survived  pclass   age     fare
1          1       1  38.0  71.2833
3          1       1  35.0  53.1000
20         0       2  35.0  26.0000
21         1       2  34.0  13.0000
23         1       1  28.0  35.5000
34         0       1  28.0  82.1708
41         0       2  27.0  21.0000
53         1       2  29.0  26.0000
56         1       2  21.0  10.5000
61         1       1  38.0  80.0000

In [65]:
#iloc
#loc와 유사하지만, index만 허용합니다.
#loc와 마찬가지고, indexing / slicing 모두 가능합니다.
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [66]:
#indexing
df.iloc[1, 3]

np.float64(38.0)

In [68]:
#Fancy Indexing
df.iloc[[0, 3, 4], [0, 1, 5, 6]]

   survived  pclass  parch   fare
0         0       3      0   7.25
3         1       1      0  53.10
4         0       3      0   8.05

In [69]:
#Slicing
df.iloc[:3, :5]

   survived  pclass     sex   age  sibsp
0         0       3    male  22.0      1
1         1       1  female  38.0      1
2         1       3  female  26.0      0

In [70]:
#isin
#특정 값의 포함 여부는 isin 함수를 통해 비교가 가능합니다. (파이썬의 in 키워드는 사용 불가 합니다.)
sample = pd.DataFrame({'name': ['kim', 'lee', 'park', 'choi'],
                        'age': [24, 27, 34, 19]
                      })
sample

   name  age
0   kim   24
1   lee   27
2  park   34
3  choi   19

In [71]:
sample['name'].isin(['kim', 'lee'])

0     True
1     True
2    False
3    False
Name: name, dtype: bool

In [72]:
sample.isin(['kim', 'lee'])

    name    age
0   True  False
1   True  False
2  False  False
3  False  False

In [73]:
#loc를 활용한 조건 필터링으로도 찰떡궁합입니다.
condition = sample['name'].isin(['kim', 'lee'])

In [74]:
sample.loc[condition]

  name  age
0  kim   24
1  lee   27

In [75]:
#연습문제
tips = sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [76]:
#tips 데이터셋 중 day가 금요일(Fri), 토요일(Sat) 만 필터링 합니다.
#tip이 $10보다 적게 낸 데이터만 필터링합니다.
#컬럼은 total_bill, tip, smoker, time만 출력합니다.
#상위 10개 행만 출력합니다.
cond1 = tips['day'].isin(['Fri', 'Sat'])
cond2 = tips['tip'] < 10
tips.loc[cond1 & cond2, ['total_bill', 'tip', 'smoker', 'time']].head(10)

    total_bill   tip smoker    time
19       20.65  3.35     No  Dinner
20       17.92  4.08     No  Dinner
21       20.29  2.75     No  Dinner
22       15.77  2.23     No  Dinner
23       39.42  7.58     No  Dinner
24       19.82  3.18     No  Dinner
25       17.81  2.34     No  Dinner
26       13.37  2.00     No  Dinner
27       12.69  2.00     No  Dinner
28       21.70  4.30     No  Dinner

In [78]:
#나이가 30살 이상 남자 승객 조건 필터링
#fare를 많이 낸 순서로 내림차순 정렬
#상위 10개
df = sns.load_dataset("titanic")
cond = (df['age'] >= 30) & (df['sex'] == 'male')
result_df = df.loc[cond].sort_values(by='fare', ascending=False).head(10)
result_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
332,0,1,male,38.0,0,1,153.4625,S,First,man,True,C,Southampton,no,False
660,1,1,male,50.0,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
390,1,1,male,36.0,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
659,0,1,male,58.0,0,2,113.2750,C,First,man,True,D,Cherbourg,no,False
698,0,1,male,49.0,1,1,110.8833,C,First,man,True,C,Cherbourg,no,False
544,0,1,male,50.0,1,0,106.4250,C,First,man,True,C,Cherbourg,no,False
245,0,1,male,44.0,2,0,90.0000,Q,First,man,True,C,Queenstown,no,False